import { seasonConfigSchema, type ProductionConfig } from '@/lib/schema';

const seasonContent = seasonConfigSchema.parse({
  id: '2026-spring',
  title: 'Activate 2026 Spring Season',
  activeProductionSlug: 'psyche-and-eros',
  productions: [
    {
      id: 'production-psyche-and-eros',
      slug: 'psyche-and-eros',
      title: 'Psyche and Eros',
      seasonLabel: 'April 2026 parent signup',
      venue: 'Activate Community Theatre',
      blurb:
        'Our families keep this production running and ensure our kids have the best experience. Pick a meal, cleanup block, concessions shift, and donate concession items.',
      coverageNote:
        'Information updates live after each signup so the parent leads can see what still needs coverage.',
      organizerSummary:
        'Use the secret organizer link to review grouped claims and export a simple CSV.',
      lanes: [
        {
          id: 'meals',
          title: 'Cast and Crew Meals',
          shortTitle: 'Meals',
          description:
            'Moms - please sign up to help with one meal. Coordinate with the other two moms. Plan on the cast eating a lot, they get hungry! Please bring dinner/dessert to CCC kitchen, and be set up and ready to serve by 5pm. You will help set up, serve, & clean up. Please make sure there is an option for one soy allergy (soy sauce is fine) and one gluten allergy.',
          emphasis: 'Rose lane',
          rows: [
            {
              id: 'meal-2026-04-14',
              category: 'meals',
              type: 'meal',
              title: 'Dress rehearsal dinner',
              summary: 'Monday, April 14 for 50 students and crew.',
              details: ['Be ready to serve by 5:00 PM'],
              dateLabel: 'Mon, April 14',
              capacity: 3,
              unitLabel: 'spots',
              noteHint: 'Share the meal plan or dietary notes.',
            },
            {
              id: 'meal-2026-04-20',
              category: 'meals',
              type: 'meal',
              title: 'Dress rehearsal dinner',
              summary: 'Monday, April 20 for 50 students and crew.',
              details: ['Be ready to serve by 5:00 PM'],
              dateLabel: 'Mon, April 20',
              capacity: 3,
              unitLabel: 'spots',
              noteHint: 'Share the meal plan or dietary notes.',
            },
            {
              id: 'meal-2026-04-21',
              category: 'meals',
              type: 'meal',
              title: 'Tuesday show dinner',
              summary: 'Tuesday, April 21 for 50 students between shows.',
              details: [],
              dateLabel: 'Tue, April 21',
              capacity: 3,
              unitLabel: 'spots',
              noteHint: 'Share the meal plan or dietary notes.',
            },
            {
              id: 'meal-2026-04-23',
              category: 'meals',
              type: 'meal',
              title: 'Thursday show dinner',
              summary: 'Thursday, April 23 for 50 students between shows.',
              details: [],
              dateLabel: 'Thu, April 23',
              capacity: 3,
              unitLabel: 'spots',
              noteHint: 'Share the meal plan or dietary notes.',
            },
            {
              id: 'meal-2026-04-24',
              category: 'meals',
              type: 'meal',
              title: 'Friday show dinner',
              summary: 'Friday, April 24 for 50 students between shows.',
              details: [],
              dateLabel: 'Fri, April 24',
              capacity: 3,
              unitLabel: 'spots',
              noteHint: 'Share the meal plan or dietary notes.',
            },
            {
              id: 'meal-2026-04-25-matinee',
              category: 'meals',
              type: 'meal',
              title: 'Saturday matinee lunch',
              summary: 'Saturday, April 25 for 50 students between shows.',
              details: [],
              dateLabel: 'Sat, April 25',
              capacity: 3,
              unitLabel: 'spots',
              noteHint: 'Share the meal plan or dietary notes.',
            },
            {
              id: 'meal-2026-04-25-evening',
              category: 'meals',
              type: 'meal',
              title: 'Saturday show dinner',
              summary: 'Saturday, April 25 for 50 students between shows.',
              details: [],
              dateLabel: 'Sat, April 25',
              capacity: 3,
              unitLabel: 'spots',
              noteHint: 'Share the meal plan or dietary notes.',
            },
          ],
        },
        {
          id: 'cleanup',
          title: 'Cleanup Crew',
          shortTitle: 'Cleanup - Please sign up for 1-2 spots',
          description:
            'Remember to check in soon after the play ends to get your cleaning assignments, and then check with the cleaning coordinator again before leaving. Reset the lobby, collect trash, and help us leave the space quickly after each performance.',
          emphasis: 'Gold lane',
          rows: [
            {
              id: 'cleanup-2026-04-21',
              category: 'cleanup',
              type: 'volunteer',
              title: 'Tuesday cleanup team',
              summary: 'Tuesday, April 21 after curtain.',
              details: ['10:00 PM to 10:45 PM', 'Light sweeping and reset'],
              dateLabel: 'Tue, April 21',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'cleanup-2026-04-23',
              category: 'cleanup',
              type: 'volunteer',
              title: 'Thursday cleanup team',
              summary: 'Thursday, April 23 after curtain.',
              details: ['10:00 PM to 10:45 PM', 'Light sweeping and reset'],
              dateLabel: 'Thu, April 23',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'cleanup-2026-04-24',
              category: 'cleanup',
              type: 'volunteer',
              title: 'Friday cleanup team',
              summary: 'Friday, April 24 after curtain.',
              details: ['10:00 PM to 10:45 PM', 'Light sweeping and reset'],
              dateLabel: 'Fri, April 24',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'cleanup-2026-04-25-matinee',
              category: 'cleanup',
              type: 'volunteer',
              title: 'Saturday matinee cleanup team',
              summary: 'Saturday, April 25 after curtain.',
              details: ['10:00 PM to 10:45 PM', 'Light sweeping and reset'],
              dateLabel: 'Sat, April 25',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'cleanup-2026-04-25-evening',
              category: 'cleanup',
              type: 'volunteer',
              title: 'Saturday evening cleanup team',
              summary: 'Saturday, April 25 after curtain.',
              details: ['10:00 PM to 10:45 PM', 'Light sweeping and reset'],
              dateLabel: 'Sat, April 25',
              capacity: 3,
              unitLabel: 'spots',
            },
          ],
        },
        {
          id: 'concessions',
          title: 'Concessions Help',
          shortTitle: 'Concessions',
          description:
            'Responsible teens can sign up to help, but we need at least 2 adults each evening. Arrive at least 60 min before the play begins to help set up. Stay after the play to help clean up. Cover the stand before house opens and at intermission.',
          emphasis: 'Sea lane',
          rows: [
            {
              id: 'concessions-2026-04-21',
              category: 'concessions',
              type: 'volunteer',
              title: 'Opening night concessions',
              summary: 'Tuesday, April 21 from 6:00 PM to intermission.',
              details: ['Cashbox and Square setup provided', 'Two adults preferred'],
              dateLabel: 'Tue, April 21',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'concessions-2026-04-23',
              category: 'concessions',
              type: 'volunteer',
              title: 'Thursday night concessions',
              summary: 'Thursday, April 23 from 6:00 PM to intermission.',
              details: ['Cashbox and Square setup provided', 'Two adults preferred'],
              dateLabel: 'Thu, April 23',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'concessions-2026-04-24',
              category: 'concessions',
              type: 'volunteer',
              title: 'Friday night concessions',
              summary: 'Friday, April 24 from 6:00 PM to intermission.',
              details: ['Cashbox and Square setup provided', 'Two adults preferred'],
              dateLabel: 'Fri, April 24',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'concessions-2026-04-25-matinee',
              category: 'concessions',
              type: 'volunteer',
              title: 'Saturday matinee concessions',
              summary: 'Saturday, April 25 from 1:00 PM to intermission.',
              details: ['Cashbox and Square setup provided', 'Two adults preferred'],
              dateLabel: 'Sat, April 25',
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'concessions-2026-04-25-evening',
              category: 'concessions',
              type: 'volunteer',
              title: 'Saturday evening concessions',
              summary:
                'Saturday, April 25 from 6:00 PM to curtain open. Volunteer parents will cover the show so parents can watch the finale. Please assist during intermission.',
              details: ['Cashbox and Square setup provided', 'Two adults preferred'],
              dateLabel: 'Sat, April 25',
              capacity: 3,
              unitLabel: 'spots',
            },
          ],
        },
        {
          id: 'donations',
          title: 'Concessions Donations',
          shortTitle: 'Donations',
          description:
            'Option 1-Pay me ( @Jessica-Ellis-43 ) and I will buy all of this at Sam\'s Club. I listed all of the prices (incl. tax) below. Please send the money BY FRIDAY, APRIL 17. If you would prefer to bring the items- they need to be sent with your youth no later than MON, Apr 20 (which is the practice before the 1st performance). Please note ACTIVATE CONCESSIONS and your LAST NAME!',
          emphasis: 'Sky lane',
          rows: [
            {
              id: 'donation-nacho-cheese',
              category: 'donations',
              type: 'donation',
              title: 'Nacho Cheese',
              summary: '$10.58 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'donation-tortilla-rounds',
              category: 'donations',
              type: 'donation',
              title: 'Case of Tortilla Rounds',
              summary: '$14.55 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'donation-nacho-trays',
              category: 'donations',
              type: 'donation',
              title: 'Case of Nacho Trays',
              summary: '$24.32 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 1,
              unitLabel: 'spots',
            },
            {
              id: 'donation-water-40-count',
              category: 'donations',
              type: 'donation',
              title: 'Case of 40 Count Water Bottles',
              summary: '$4.22 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'donation-creamies',
              category: 'donations',
              type: 'donation',
              title: 'Creamies Variety Pack',
              summary: '$13.23 for a 30 count variety pack at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'donation-soda-screw-lid',
              category: 'donations',
              type: 'donation',
              title: '24 Count Soda with Screw Lid',
              summary: '16 oz 24 pack, about $18.00 at Sam\'s Club depending on variety.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 5,
              unitLabel: 'spots',
            },
            {
              id: 'donation-capri-sun',
              category: 'donations',
              type: 'donation',
              title: 'Capri-Sun or Juice Type Drinks',
              summary: '40 count Capri-Sun is $14.82 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 3,
              unitLabel: 'spots',
            },
            {
              id: 'donation-hot-dogs-buns',
              category: 'donations',
              type: 'donation',
              title: 'Hot Dogs and Buns',
              summary: '24 pack hot dogs are $13.74 and buns are $3.48 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 1,
              unitLabel: 'spots',
            },
            {
              id: 'donation-condiment-pack',
              category: 'donations',
              type: 'donation',
              title: 'Heinz Condiment Picnic Pack',
              summary: '$10.58 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 1,
              unitLabel: 'spots',
            },
            {
              id: 'donation-jalapenos',
              category: 'donations',
              type: 'donation',
              title: 'Jalapenos',
              summary: '$6.13 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 1,
              unitLabel: 'spots',
            },
            {
              id: 'donation-sour-cream',
              category: 'donations',
              type: 'donation',
              title: 'Sour Cream',
              summary: '$5.27 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 2,
              unitLabel: 'spots',
            },
            {
              id: 'donation-chili',
              category: 'donations',
              type: 'donation',
              title: 'Chili',
              summary: 'Canned or homemade. 108 oz is about $18.00 with tax at Sam\'s Club.',
              details: [
                'Please specify whether it is homemade or store bought.',
                'If homemade, say what day you will bring it.',
              ],
              capacity: 5,
              unitLabel: 'spots',
              noteHint: 'Use the form notes to say whether you are sending money or bringing the item on Monday.',
            },
            {
              id: 'donation-onions',
              category: 'donations',
              type: 'donation',
              title: 'Onions',
              summary: '$5.11 for a 5 pound bag at Sam\'s Club.',
              details: [
                'Please do not pre-chop them.',
                'Use the form notes to say whether you are sending money or bringing the item on Monday.',
              ],
              capacity: 1,
              unitLabel: 'spots',
            },
            {
              id: 'donation-red-vines',
              category: 'donations',
              type: 'donation',
              title: 'Case of Red Vines',
              summary: '4 oz 15 pack for $14.82 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 2,
              unitLabel: 'spots',
            },
            {
              id: 'donation-ring-pops',
              category: 'donations',
              type: 'donation',
              title: 'Ring Pops',
              summary: '44 count for $17.78 at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 1,
              unitLabel: 'spots',
            },
            {
              id: 'donation-skittles-starburst',
              category: 'donations',
              type: 'donation',
              title: 'Skittles and Starburst Variety Pack',
              summary: '30 count for $31.78 plus tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 2,
              unitLabel: 'spots',
            },
            {
              id: 'donation-chocolate-bars',
              category: 'donations',
              type: 'donation',
              title: 'Chocolate Bar Variety Pack',
              summary: '30 count for $35.48 with tax at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 2,
              unitLabel: 'spots',
            },
            {
              id: 'donation-airheads',
              category: 'donations',
              type: 'donation',
              title: 'AirHeads',
              summary: '90 count for $15.56 at Sam\'s Club.',
              details: ['Use the form notes to say whether you are sending money or bringing the item on Monday.'],
              capacity: 1,
              unitLabel: 'spots',
            },
            {
              id: 'donation-small-candy',
              category: 'donations',
              type: 'donation',
              title: 'Individual Small Wrapped Candy',
              summary: 'About $12 depending on variety.',
              details: [
                'Think small: suckers, hard candy, bite-sized candy bars, and similar treats.',
                'Great for little kids with a small budget.',
                'Use the form notes to say what you are bringing and whether you are sending money or bringing the item on Monday.',
              ],
              capacity: 4,
              unitLabel: 'spots',
            },
            {
              id: 'donation-rice-krispie-treats',
              category: 'donations',
              type: 'donation',
              title: 'Rice Krispie Treats - Wrapped',
              summary: 'Homemade goods for Tuesday 21 and Thursday 23.',
              details: ['Please send the date you will bring them in the form notes.'],
              capacity: 2,
              unitLabel: 'spots',
              noteHint: 'Use the form notes for the date and whether someone should expect them Tuesday or Thursday.',
            },
            {
              id: 'donation-giant-brownies',
              category: 'donations',
              type: 'donation',
              title: 'Giant Brownies - Wrapped',
              summary: 'Homemade goods for Tuesday 21 and Friday 24.',
              details: ['Please send the date you will bring them in the form notes.'],
              capacity: 2,
              unitLabel: 'spots',
              noteHint: 'Use the form notes for the date and whether someone should expect them Tuesday or Friday.',
            },
            {
              id: 'donation-cookies-homemade',
              category: 'donations',
              type: 'donation',
              title: 'Cookies - Wrapped',
              summary: 'Homemade goods for Tuesday 21 and Saturday 25.',
              details: ['Please send the date you will bring them in the form notes.'],
              capacity: 2,
              unitLabel: 'spots',
              noteHint: 'Use the form notes for the date and whether someone should expect them Tuesday or Saturday.',
            },
            {
              id: 'donation-other-homemade',
              category: 'donations',
              type: 'donation',
              title: 'Other Homemade Items',
              summary: 'Share what you are bringing in the form notes.',
              details: ['Include what you are bringing and the best contact phone number in the form.'],
              capacity: 2,
              unitLabel: 'spots',
            },
          ],
        },
      ],
    },
  ],
});

export function getSeasonContent() {
  return seasonContent;
}

export function getActiveProductionContent(): ProductionConfig {
  const production = seasonContent.productions.find(
    (item) => item.slug === seasonContent.activeProductionSlug
  );

  if (!production) {
    throw new Error('Active Activate production config was not found.');
  }

  return production;
}
